// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV_S4A5D0iXzmuYDn0oI5h3nkv9KjFhmg',
    appId: '1:484906751093:web:77e2f5c535810aaf89143c',
    messagingSenderId: '484906751093',
    projectId: 'korhazappdb',
    authDomain: 'korhazappdb.firebaseapp.com',
    storageBucket: 'korhazappdb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV5AZu9NEqj9VKrsloR6XYAzVHg-lXMyM',
    appId: '1:484906751093:android:2f9d1cb347edc0da89143c',
    messagingSenderId: '484906751093',
    projectId: 'korhazappdb',
    storageBucket: 'korhazappdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkeNTmSzN7-iovamLog5Dyq9I8uoUkMYU',
    appId: '1:484906751093:ios:bb6041851f9f85e489143c',
    messagingSenderId: '484906751093',
    projectId: 'korhazappdb',
    storageBucket: 'korhazappdb.firebasestorage.app',
    iosBundleId: 'com.example.korhazApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkeNTmSzN7-iovamLog5Dyq9I8uoUkMYU',
    appId: '1:484906751093:ios:bb6041851f9f85e489143c',
    messagingSenderId: '484906751093',
    projectId: 'korhazappdb',
    storageBucket: 'korhazappdb.firebasestorage.app',
    iosBundleId: 'com.example.korhazApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV_S4A5D0iXzmuYDn0oI5h3nkv9KjFhmg',
    appId: '1:484906751093:web:45fc35685debe00589143c',
    messagingSenderId: '484906751093',
    projectId: 'korhazappdb',
    authDomain: 'korhazappdb.firebaseapp.com',
    storageBucket: 'korhazappdb.firebasestorage.app',
  );
}
